language: python
python:
- '3.6'
script:
- python setup.py test
deploy:
  provider: pypi
  user: mathiasbrito
  password:
    secure: dVYFfJme7qRuv/sStAm3PBVuPF2lyj2FHEUU3ESLJFwY60v7AvL/35MoBBq1lsr/N7zghU+pbeV+nJb9P8Bd9UqjZ1639/khPqOZ7grD0WUcLqhzJp9g6ZVK2C15fhrVtF0cQEb15smsLx1L1Ic9Blxvj97Rw74idiRxUyaJnwwrLY6yvUq5VloD5c7xv/3AGlIkxlO4WSQVeVC/GAn1qMFCE4gAWXW/ExMwfHwth3o4i1MiB/aIACekULchax0ubpqVHrqYhb6CchMyIzRhEPXFqVLmFBiWldu2g7kwEIwfkf7OTL0im/GkZXT49QY4habqcllYCAHNJKhL7bHWze+RpgW3rnM4SefcmJayuqIocKYe+0G7WPIfkHEHEgQoIEYEid8sDU2UQKC6xO975Wg43LXzMYaIgXc9tmRF4B63ZdA0197MYRmQcwyaRgGs/md8yFymoHgOotk8nQQs059XRW1LQdRSL4Yg2RsRr5QBJDWdA2t2IB0FPKShvKFd7yROTQqvx8BPHgmxVBJ4qqnm7G9ot4pgo2i9qsdRz7zpEtcaeb7CSZEUIaNVlqZoXUqSq8W49Sdx0E6NDJwFC75PP15n/Mu3RRQ9t2sl3H06exSYeTFK7JPgqMWrXXK96b0vB8OYJzfPhW4kbqjc3UKdJWw3UKjQGt9xvslalq0=
  on:
    branch: master
    python: 3.6
